/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import { Mesh, MeshStandardMaterial } from 'three';
import { useGLTF } from '@react-three/drei';
import { useControls } from "leva";
import { useFrame } from '@react-three/fiber';
import { useRef, useState } from 'react';
import type { LilyProps } from '../types/lily';
import { Ripple } from './Ripple';

export function LilyPad({ position }: LilyProps) {
  const [isActive, setIsActive] = useState(false);

  const { nodes } = useGLTF('/water-lily.glb')
  const lilyPadRef = useRef<Mesh>(null); // On stocke le mesh qu'on veut animer dans une ref
  
  //Animation 
  useFrame((state, delta) => { 
    if (lilyPadRef.current && isActive == true) {
      lilyPadRef.current.rotation.z += delta * 1 //
    }
  });
  

  return (
    <>
      <mesh
        onPointerOver={() => setIsActive(true)} 
        onPointerOut={() => setIsActive(false)}
        ref={lilyPadRef}
        castShadow
        receiveShadow
        geometry={nodes.Circle001.geometry}
        material={new MeshStandardMaterial({ color: '#00BB77'})}
        // position={[lilyPadPosition.x,lilyPadPosition.y,lilyPadPosition.z]}
        position={[position.x, position.y, position.z]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.012}
      />
      <Ripple position={position} />
    </>
  )
}

useGLTF.preload('/water-lily.glb')

