/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import { Mesh, MeshStandardMaterial } from 'three';
import { useGLTF } from '@react-three/drei';
import { useControls } from "leva";
import { useRef, useState } from 'react';
import { useFrame } from '@react-three/fiber';
import type { LilyProps } from '../types/lily';
import { allLilyMaterials } from '../reusables/materials';
import { Ripple } from './Ripple';

export function Lily({ position }: LilyProps) {
  const lilyRef = useRef<Mesh>(null); // On stocke le mesh qu'on veut animer dans une ref
	const [isActive, setIsActive] = useState(false);
  const [lilyMaterialIndex, setLilyMaterialIndex] = useState(0)
  const { nodes } = useGLTF('/water-lily.glb')

  //Leva GUI
  const { lilyPadColor: lilyPadColor, lilyColor: lilyColor, lilyPistilColor: lilyPistilColor, lilyPosition: lilyPosition, lilyPadPosition: lilyPadPosition } = useControls('Lily', {
        lilyPadColor: {
            label: 'Lily pad color', 
            value: '#00BB77'
        },
        lilyColor: {
            label: 'Lily color', 
            value: '#ff99c3'
        },
        lilyPistilColor: {
            label: 'Lily color', 
            value: '#fdfd96'
        },
        lilyPosition: {
            label: 'lilyPosition',
            value: { x: 0, y: 0.01, z: 0 },
            min: -20,
            max: 20
        },
        lilyPadPosition: {
            label: 'lilyPadPosition',
            value: { x: 0, y: 0, z: 0 },
            min: -20,
            max: 20
        }
    })

  //Color change
  const changeColor = () => {
    if (lilyMaterialIndex < allLilyMaterials.length) {
      setLilyMaterialIndex((index) => index+1)
      console.log(lilyMaterialIndex)
    } 
    if (lilyMaterialIndex >= allLilyMaterials.length) {
      setLilyMaterialIndex(0)
    }
  }

	//Animation 
	useFrame((state, delta) => { 
		if (lilyRef.current && isActive == true) {
			lilyRef.current.rotation.y += delta * 1 //
		}
	});

  return (
    <>
      <mesh 
        onPointerOver={() => setIsActive(true)} 
        onPointerOut={() => setIsActive(false)} 
        onClick={changeColor}
        ref={lilyRef} 
        position={[position.x, position.y, position.z]}
        >  
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle001.geometry}
          material={new MeshStandardMaterial({ color: lilyPadColor})}
          position={[lilyPadPosition.x,lilyPadPosition.y,lilyPadPosition.z]}
          rotation={[Math.PI / 2, 0, 2]}
          scale={0.01}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Icosphere031.geometry}
          // material={new MeshStandardMaterial({ color: 0xfdfd96})}
          material={new MeshStandardMaterial({ color: lilyPistilColor})}
          position={[lilyPosition.x, lilyPosition.y, lilyPosition.z]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}>
            <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane007.geometry}
            // material={new MeshStandardMaterial({ color: lilyColor})}
            material={allLilyMaterials[lilyMaterialIndex]}
            position={[0, 0, -7.4]}
            />
            <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane009.geometry}
            // material={new MeshStandardMaterial({ color: lilyColor})}
            material={allLilyMaterials[lilyMaterialIndex]}
            position={[-2.7, -24.5, -0.7]}
            />
        </mesh>
      </mesh>
      <Ripple position={position} />
    </>
  )
}

useGLTF.preload('/water-lily.glb')

